"""3rd edition. relations

Revision ID: 077a50dbace8
Revises: 2cfff4b4689a
Create Date: 2026-01-29 15:36:37.234974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '077a50dbace8'
down_revision: Union[str, Sequence[str], None] = '2cfff4b4689a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'post_id', 'device_id')
    )
    op.create_table('user_search',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('cnt', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post_media', 'id')
    op.drop_column('post_tag', 'id')
    op.drop_column('tag', 'created_at')
    op.drop_column('tag', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tag', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('post_tag', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.add_column('post_media', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    op.drop_table('user_search')
    op.drop_table('likes')
    op.drop_table('devices')
    # ### end Alembic commands ###
