""" boglanishda xatolik post va user jadvallari 

Revision ID: 23cd4d9b052d
Revises: 02e8e700ee45
Create Date: 2026-02-01 05:38:13.509653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cd4d9b052d'
down_revision: Union[str, Sequence[str], None] = '02e8e700ee45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
