"""new fields on users model

Revision ID: 701365b23a81
Revises: 23cd4d9b052d
Create Date: 2026-02-07 12:40:26.411736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701365b23a81'
down_revision: Union[str, Sequence[str], None] = '23cd4d9b052d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('users', sa.Column('deleted_email', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('users', 'profession_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profession_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'deleted_email')
    op.alter_column('comment', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
