"""we added new tables

Revision ID: b550689eedf9
Revises: 3a86566ca5fb
Create Date: 2026-02-01 04:04:09.880372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b550689eedf9'
down_revision: Union[str, Sequence[str], None] = '3a86566ca5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    # ### end Alembic commands ###
