"""all to true

Revision ID: c772fa4f5727
Revises: b69c70f2b96b
Create Date: 2026-02-07 13:12:22.530396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c772fa4f5727'
down_revision: Union[str, Sequence[str], None] = 'b69c70f2b96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###
